In [1]:
import geopandas as gpd

m1=gpd.read_file("World_Cities.zip")
m2=gpd.read_file("World_Countries.zip")
m3=gpd.read_file("World_Hydrography.zip")

In [2]:
m1.to_file("testmap.gpkg", driver="GPKG",layer="cities")
m2.to_file("testmap.gpkg", driver="GPKG",layer="countries")
m3.to_file("testmap.gpkg", driver="GPKG",layer="rivers")

In [11]:
gpd.list_layers("https://github.com/CienciaDeDatosEspacial/dataSets/raw/refs/heads/main/WORLD/worldMaps.gpkg")

         name    geometry_type
0  indicators          Unknown
1   countries     MultiPolygon
2      rivers  MultiLineString
3      cities            Point

In [5]:
m2.geometry.geom_type.value_counts()

Polygon         137
MultiPolygon    115
Name: count, dtype: int64

In [8]:
countries=gpd.read_file("africa_8857.gpkg",layer="countries")
countries

,Country,iso2,iso3,region,fragility,co2,sq_km,num_airports,population,mobiles,geometry
0,ALGERIA,DZ,DZA,AFRICA,75.4,151633000,2381740,95,47022473,51500000,"MULTIPOLYGON (((-461528.863 3785845.186, -4603..."
1,ANGOLA,AO,AGO,AFRICA,87.8,19362000,1246700,107,37202061,25700000,"MULTIPOLYGON (((1252211.409 -594965.255, 12523..."
2,BOTSWANA,BW,BWA,AFRICA,59.5,5965000,581730,122,2450668,4440000,"MULTIPOLYGON (((2419408.33 -3115326.798, 24184..."
3,BENIN,BJ,BEN,AFRICA,73.6,6903000,112622,10,14697052,16400000,"MULTIPOLYGON (((260709.591 982516.929, 260641...."
4,BURUNDI,BI,BDI,AFRICA,98.2,715000,27830,6,13590102,8650000,"MULTIPOLYGON (((2952925.496 -382651.512, 29522..."
5,CHAD,TD,TCD,AFRICA,108.5,1771000,1284000,44,19093595,12100000,"MULTIPOLYGON (((1350097.646 1279278.576, 13743..."
6,CONGO,CG,COG,AFRICA,92.5,4523000,342000,56,6097665,5870000,"MULTIPOLYGON (((1520600.468 -506427.414, 15196..."
7,DEMOCRATIC REPUBLIC OF THE CONGO,CD,COD,AFRICA,110.2,2653000,2344858,273,115403027,49800000,"MULTIPOLYGON (((1538566.418 -752199.639, 15221..."
8,CAMEROON,CM,CMR,AFRICA,97.0,7105000,475440,37,30966105,26200000,"MULTIPOLYGON (((892970.126 503742.219, 890896...."
9,COMOROS,KM,COM,AFRICA,81.7,326000,2235,3,900141,934000,"MULTIPOLYGON (((4120153.825 -1528074.693, 4117..."
10,CENTRAL AFRICAN REPUBLIC,CF,CAF,AFRICA,108.9,285000,622984,43,5650957,1830000,"MULTIPOLYGON (((1956531.22 580948.208, 1956855..."
11,CAPE VERDE,CV,CPV,AFRICA,66.6,1002000,4033,10,611014,590000,"MULTIPOLYGON (((-2372168.678 2157250.913, -237..."
12,DJIBOUTI,DJ,DJI,AFRICA,85.1,610000,23200,10,994974,574000,"MULTIPOLYGON (((4100363.014 1459633.45, 409873..."
13,EGYPT,EG,EGY,AFRICA,88.4,235137000,1001450,73,111247248,106000000,"MULTIPOLYGON (((2929884.448 3739061.904, 29257..."
14,EQUATORIAL GUINEA,GQ,GNQ,AFRICA,82.6,4528000,28051,7,1795834,893000,"MULTIPOLYGON (((848613.584 451776.733, 847717...."
15,ETHIOPIA,ET,ETH,AFRICA,94.2,16798000,1104300,58,118550298,71400000,"MULTIPOLYGON (((4348407.004 704825.781, 433784..."
16,GAMBIA,GM,GMB,AFRICA,83.9,606000,11300,1,2523327,2680000,"MULTIPOLYGON (((-1446275.595 1725385.467, -144..."
17,GABON,GA,GAB,AFRICA,70.5,2651000,267667,42,2455105,3000000,"MULTIPOLYGON (((1245037.958 -304172.942, 12461..."
18,GHANA,GH,GHA,AFRICA,65.9,18093000,238533,11,34589092,33400000,"MULTIPOLYGON (((30803.19 774811.662, 33800.548..."
19,GUINEA,GN,GIN,AFRICA,99.4,2981000,245857,16,13986179,13800000,"MULTIPOLYGON (((-1197497.293 1234654.212, -120..."
20,IVORY COAST,CI,CIV,AFRICA,92.1,11880000,322463,29,29981758,53600000,"MULTIPOLYGON (((-508643.283 666464.559, -50703..."
21,KENYA,KE,KEN,AFRICA,93.5,17709000,580367,368,58246378,66700000,"MULTIPOLYGON (((3249398.861 -128734.057, 32496..."
22,LIBERIA,LR,LBR,AFRICA,90.2,1346000,111369,19,5437249,1650000,"MULTIPOLYGON (((-1016279.263 798148.399, -1018..."
23,LESOTHO,LS,LSO,AFRICA,79.7,736000,30355,34,2227548,1600000,"MULTIPOLYGON (((2602085.054 -3763113.47, 25909..."
24,LIBYA,LY,LBY,AFRICA,92.2,38297000,1759540,75,7361263,13900000,"MULTIPOLYGON (((2264190.906 3484227.626, 22647..."
25,MADAGASCAR,MG,MDG,AFRICA,80.9,4218000,587041,93,29452714,25400000,"MULTIPOLYGON (((4360223.459 -1997616.554, 4360..."
26,MALAWI,MW,MWI,AFRICA,83.3,1542000,118484,27,21763309,12900000,"MULTIPOLYGON (((3137727.94 -1791419.861, 31361..."
27,MALI,ML,MLI,AFRICA,94.5,5679000,1240192,30,21990607,25900000,"MULTIPOLYGON (((-935200.116 1543157.865, -9395..."
28,MOROCCO,MA,MAR,AFRICA,73.0,60200000,716550,48,37387585,55900000,"MULTIPOLYGON (((-301145.548 3969277.852, -3041..."
29,MAURITIUS,MU,MUS,AFRICA,38.9,7191000,2040,5,1310504,2100000,"MULTIPOLYGON (((5912204.63 -2503201.611, 59137..."
30,MAURITANIA,MR,MRT,AFRICA,90.1,4041000,1030700,25,4328040,5360000,"MULTIPOLYGON (((-584001.572 2913751.517, -5832..."
31,MOZAMBIQUE,MZ,MOZ,AFRICA,88.7,7753000,799380,92,33350954,15000000,"MULTIPOLYGON (((3096913.076 -2212900.375, 3096..."
32,NIGER,NE,NER,AFRICA,96.2,2374000,1267000,26,26342784,14200000,"MULTIPOLYGON (((665104.319 1662603.732, 656979..."
33,NIGERIA,NG,NGA,AFRICA,98.5,104494000,923768,50,236747130,224000000,"MULTIPOLYGON (((1126046.792 936261.483, 112183..."
34,GUINEA-BISSAU,GW,GNB,AFRICA,95.5,342000,36125,7,2132325,2760000,"MULTIPOLYGON (((-1415485.832 1506098.798, -141..."
35,RWANDA,RW,RWA,AFRICA,87.5,1189000,26338,8,13623302,12800000,"MULTIPOLYGON (((2779024.537 -352595.052, 27783..."
36,SEYCHELLES,SC,SYC,AFRICA,55.2,1156000,455,16,98187,165000,"MULTIPOLYGON (((5311204.235 -614989.73, 531042..."
37,SENEGAL,SN,SEN,AFRICA,77.2,10696000,196722,20,18847519,22400000,"MULTIPOLYGON (((-1358041.897 1622403.662, -136..."
38,SIERRA LEONE,SL,SLE,AFRICA,86.8,899000,71740,8,9121049,8230000,"MULTIPOLYGON (((-1035249.697 967636.346, -1036..."
39,SUDAN,SD,SDN,AFRICA,108.0,17319000,1861484,45,50467278,34700000,"MULTIPOLYGON (((3254641.759 1277089.044, 32531..."
40,TOGO,TG,TGO,AFRICA,87.4,2244000,56785,7,8917994,7050000,"MULTIPOLYGON (((157941.023 966087.138, 157439...."
41,SAO TOME AND PRINCIPE,ST,STP,AFRICA,71.1,173000,964,2,223561,152000,"MULTIPOLYGON (((708718.699 196645.538, 703791...."
42,TUNISIA,TN,TUN,AFRICA,70.1,23692000,163610,14,12048847,16400000,"MULTIPOLYGON (((660584.464 4244523.474, 660791..."
43,TANZANIA,TZ,TZA,AFRICA,80.1,11491000,947300,206,67462121,70200000,"MULTIPOLYGON (((3652902.884 -1461857.383, 3645..."
44,UGANDA,UG,UGA,AFRICA,95.3,5841000,241038,39,49283041,42100000,"MULTIPOLYGON (((3150661.019 -128446.719, 31364..."
45,BURKINA FASO,BF,BFA,AFRICA,83.9,4444000,274200,49,23042199,24700000,"MULTIPOLYGON (((87175.652 1408549.889, 77106.7..."
46,NAMIBIA,None,NAM,AFRICA,66.4,3831000,824292,259,2803660,2600000,"MULTIPOLYGON (((1340141.319 -2876996.569, 1340..."
47,ESWATINI,SZ,SWZ,AFRICA,85.3,1224000,17364,16,1138089,1520000,"MULTIPOLYGON (((2808547.901 -3376024.075, 2806..."
48,ZAMBIA,ZM,ZMB,AFRICA,85.7,6798000,752618,120,20799116,21200000,"MULTIPOLYGON (((2847683.539 -1913931.054, 2847..."
49,ZIMBABWE,ZW,ZWE,AFRICA,99.5,7902000,390757,144,17150352,15000000,"MULTIPOLYGON (((3010756.809 -2710383.71, 30087..."
50,SOUTH SUDAN,SS,SSD,AFRICA,112.2,1778000,644329,89,12703714,6170000,"MULTIPOLYGON (((3254641.759 1277089.044, 32538..."